Feat/init project
csc-667-spring-2023-roberts/term-project-frenchies pull request #2
Opened 2023-03-19 06:23 UTC by Cleopha

## Description

- Add PR and Issue Template
- Add workflow: Jest Test and Lint
- Simple bakcend in Express Typescript which allows to return .ejs
- Docker-compose which will allow to make tests with a postman collection afterwards

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue).
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention).
- [x] New feature (non-breaking change that adds functionality).
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality).
- [ ] Documentation update (change added to any kind of documentation).

## Checklist

- [x] I have assigned this PR to myself.
- [x] I have added at least 1 reviewer.
- [x] I have added the relevant labels.
- [ ] I have updated the official documentation.
- [ ] I have added sufficient documentation in code.

## Testing

- [x] I have tested this code with the official test suite.
- [x] I have tested this code manually.

2023-03-19 22:20 UTC, 0xpanoramix requested changes

2023-03-19 22:20 UTC, 0xpanoramix commented on .github/workflows/ci.yml
> +    branches: ["master", "main", "develop", "feat/init-repo"]
No need for additional branches.

```suggestion
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
```

2023-03-19 22:20 UTC, 0xpanoramix commented on .github/workflows/ci.yml
> +      uses: actions/checkout@v2
Please use the v3.

```suggestion
      uses: actions/checkout@v3
```

2023-03-19 22:20 UTC, 0xpanoramix commented on .github/workflows/lint.yml
Can you declare this job as a parallel one in the CI configuration ?
You'll avoid code duplication.

2023-03-19 22:20 UTC, 0xpanoramix commented on backend/package.json
> +    "lint": "eslint . --ext .ts",
This will help fixing lint errors much faster.

```suggestion
    "lint": "eslint . --ext .ts",
    "lint:fix": "eslint . --ext .ts --fix",
```

2023-03-19 22:20 UTC, 0xpanoramix commented on backend/public/css/style.css
Please write code comments in english.

2023-03-19 22:20 UTC, 0xpanoramix commented on backend/src/app.ts
Can't you use aliases to declare paths in one single place instead of adding tweaks in the code ?

2023-03-19 22:20 UTC, 0xpanoramix commented on backend/src/routes/routes.ts
> +  res.render('about'  );
```suggestion
  res.render('about');
```

2023-03-19 22:20 UTC, 0xpanoramix commented on backend/views/index.ejs
Again, please write code comments, components and variables in english.

2023-03-19 22:49 UTC, Cleopha commented on .github/workflows/lint.yml
5ae983693880204de814ecacacf9d3ccfcc2cb52

2023-03-19 22:59 UTC, Cleopha commented on backend/public/css/style.css
094e533d77031bc165ae6f384c7e73b18b76b09b

2023-03-19 22:59 UTC, Cleopha commented on backend/views/index.ejs
094e533d77031bc165ae6f384c7e73b18b76b09b

2023-03-19 23:48 UTC, Cleopha commented on backend/src/app.ts
fail when I try to implement it

2023-03-20 00:13 UTC, 0xpanoramix approved these changes
LGTM!

2023-03-20 00:14 UTC, merged